### ISSUE TITLE
Library Version Mismatch

### ISSUE THREAD

**Issue by pandaaditi91-1** [mindflow-institue/DAEFormer#15]
AttributeError: 'Delaunay' object has no attribute 'vertices'

This occurs in all my runs.

**Comment by pandaaditi91-1** [comment]
Full trace: 

**Using device: cuda

Tesla V100-SXM2-16GB
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB
Namespace(root_path='./data/Synapse/train_npz', test_path='./data/Synapse/test_vol_h5', dataset='Synapse', list_dir='./lists/lists_Synapse', num_classes=9, output_dir='./model_out', max_iterations=90000, max_epochs=400, batch_size=20, num_workers=4, eval_interval=20, model_name='synapse', n_gpu=1, deterministic=1, base_lr=0.04166666666666667, img_size=224, z_spacing=1, seed=1234, zip=False, cache_mode='part', resume=None, accumulation_steps=None, use_checkpoint=False, amp_opt_level='O1', tag=None, eval=False, throughput=False, module='networks.DAEFormer.DAEFormer')
The length of train set is: 2211
111 iterations per epoch. 44400 max iterations 
  0%|                                         | 0/400 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/content/DAEFormer/train.py", line 126, in <module>
    trainer[dataset_name](args, net, args.output_dir)
  File "/content/DAEFormer/trainer.py", line 126, in trainer_synapse
    for i_batch, sampled_batch in enumerate(trainloader):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 694, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/DAEFormer/datasets/dataset_synapse.py", line 108, in __getitem__
    image,label = augment_seg(self.img_aug, image, label)
  File "/content/DAEFormer/datasets/dataset_synapse.py", line 30, in augment_seg
    image_aug = aug_det.augment_image( img )
  File "/usr/local/lib/python3.10/dist-packages/imgaug/augmenters/meta.py", line 771, in augment_image
    return self.augment_images([image], hooks=hooks)[0]
  File "/usr/local/lib/python3.10/dist-packages/imgaug/augmenters/meta.py", line 822, in augment_images
    return self.augment_batch_(
  File "/usr/local/lib/python3.10/dist-packages/imgaug/augmenters/meta.py", line 641, in augment_batch_
    batch_inaug = self._augment_batch_(
  File "/usr/local/lib/python3.10/dist-packages/imgaug/augmenters/meta.py", line 3403, in _augment_batch_
    batch_sub = self[augmenter_index].augment_batch_(
  File "/usr/local/lib/python3.10/dist-packages/imgaug/augmenters/meta.py", line 641, in augment_batch_
    batch_inaug = self._augment_batch_(
  File "/usr/local/lib/python3.10/dist-packages/imgaug/augmenters/geometric.py", line 3050, in _augment_batch_
    batch.images = self._augment_images_by_samples(batch.images,
  File "/usr/local/lib/python3.10/dist-packages/imgaug/augmenters/geometric.py", line 3099, in _augment_images_by_samples
    transformer = self._get_transformer(
  File "/usr/local/lib/python3.10/dist-packages/imgaug/augmenters/geometric.py", line 3353, in _get_transformer
    matrix.estimate(points_src[:, ::-1], points_dest[:, ::-1])
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/_geometric.py", line 984, in estimate
    for tri in self._tesselation.vertices:
AttributeError: 'Delaunay' object has no attribute 'vertices'**
